# site settings
title: Portfolio
subtitle:
email: niteshtarani510@gmail.com
description: Lead Engineer specializing in mobile and backend development. 10+ years building scalable Android apps, with expertise in iOS, cross-platform solutions, and distributed backend systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Bollineni Silas, Belathur main road, Kadugodi
city: Bengaluru
state: Karnataka
zip_code: 560067
country: India
phone: +918126287444

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/niteshtarani
  GitLab:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/niteshtarani/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
